Try loading a spec/cfg with the MC prefix before loading the
alygin/vscode-tlaplus pull request #233
Opened 2021-08-08 03:09 UTC by lemmy

file matching the current editor

Essentially, this introduce the convention that TLC-related
modules and config files are prefixed with 'MC'.

2021-08-08 03:13 UTC, lemmy commented
I have been using the feature [for a while now](https://github.com/lemmy/vscode-tlaplus/commit/0304d3a272cf908d4c17cc2a2d9db356d4063890) and find it useful.

2021-09-04 21:21 UTC, alygin requested changes
The code doesn't compile

2021-09-04 21:21 UTC, alygin commented on src/commands/checkModel.ts
> +
It looks like the closing brace is missing here.

2021-09-04 21:21 UTC, alygin commented on src/commands/checkModel.ts
> +        const n = uri.toString().replace(b.toString(), 'MC' + b);
This replacement looks very unreliable. What if, for example, the spec file is `/my_specs/spec.tla`? We'll end up searching for `/my_MCspecs/MCspec.tla`, which is incorrect.

2021-09-04 21:21 UTC, alygin commented on src/commands/checkModel.ts
> +
These lines duplicate the code that comes after the new `if`. I guess, we could just have the following flow, which is easier to read and reason about:

```typescript
if (!startsWith(...)) {
   specFiles = ...
}
if (!specFiles) {
   specFiles = ... // what we have now
}
if (!specFiles) {
   return;
}
doCheckModel(...)
```

2021-09-04 22:40 UTC, lemmy commented
Thanks for the review.  I'm happy to review the PR if we all agree that this `MC` convention (potentially extended to `MC` as prefix *and* suffix) is a good idea.   Alternatively, the extension could open a file chooser instead of offering to create a config file if it can't find a `.cfg` file for the current editor.

2021-09-21 22:52 UTC, merged

2021-09-21 22:52 UTC, lemmy commented
@alygin Please review even though this has been merged.  I"m confident but a second pair of eyes never hurts.  The reason why I've already merged is to test-drive the functionality in an internal workshop this week.